name: Release build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/pkantorowicz/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.ACTION_GITHUB_TOKEN}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack 
        run: dotnet pack --no-build --configuration Release src/NHibernate.UnitOfWork.Core/NHibernate.UnitOfWork.Core.csproj
      - name: Push 
        run: dotnet nuget push src/NHibernate.UnitOfWork.Core/bin/Release/*.nupkg --skip-duplicate --no-symbols
      - name: Tag commit
        uses: pkgdeps/git-tag-action@v2
        with:
          version: "0.1.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"